### ISSUE TITLE
Calibrationファイルを読めることにする

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#101]
## 概要

現状では、アプリを再起動すると、Calibrationの情報がなくなり、Calibrationし直さないといけない。Calibration情報ファイルをコンテナの外で保存し、再開時に保存された情報を利用するようにする。

## 要件

* Calibration情報ファイルをコンテナの外で保存する。
* Calibration情報ファイルを読んで利用する。
* 正しくマウントされるように、初期のCalibrationの情報ファイルを用意する。

## 成果物

要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコードを修正する。
* [x] masterにマージする。

**Comment by moritama312** [comment]
マージしました。クローズします。

**Comment by o0fatigue** [comment]
* 元々の `param_file.txt` のフォーマットを変えました。 一行目に、スペース区切りの数値が六個あります。それぞれ、 gazeとheadのyaw, pitch, rollになります。
* 正しくマウントされるように、初期ファイルを用意しました。検証しやすいように、顔が上向きになる状態でcalibrationをしたパラメータが入っています。
