### ISSUE TITLE
リソースを微調整する

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#105]
## 概要

現状では、メーターのリソースフィアルにずれるところがあり、それを修正したい。

## 要件

* borderのはみ出すところを修正する。
* 各画像の枠を一致にする。

## 成果物

要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] 画像を修正する。
* [x] masterにマージされる。

**Comment by moritama312** [comment]
マージしました。クローズします。
