### ISSUE TITLE
ストーリー: 離席状態を表示できる

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#17]
## 概要

運転席に人がいる(顔がある)ことを検出できない状態を「離席」状態とし、RiskyActionとして表示したい。

## デモ手順
 1. デモを起動する
 2. 画面に顔が検出できないとき「離席」となることを見せる
 3. 画面に顔が検出できると非「離席」状態となることを見せる
 4. 検出枠表示をONにして、顔検出と「離席」状態が連動することを見せる
 
## タスク
* [x] 付箋を貼り付ける
* [x] 概要、デモ手順を記述する
* [x] issue #21 RiskyActionに離席状態を表示する
* [x] スプリントレビューでデモを実施する

**Comment by nayutaya** [comment]
『検出枠表示をONにして、顔検出と「離席」状態が連動することを見せる』に関するIssueがありませんね。またこの機能については`master`ブランチにまだ取り込まれていないとのこと。

**Comment by moritama312** [comment]
デモしました。クローズします。
