### ISSUE TITLE
GUI要素の配置を設計する

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#19]
## 概要

中国デモのリソースを並びかえて、デモ画面のイメージを確認したい

## 要件

* 中国デモのリソース画像を切り貼りしてイメージを作成する
* 属性（年齢、性別、メガネ）の表示あり/なしの両方に対応できること
* RiskyActionの一番右に離席状態のアイコンを表示する場所を確保すること
* Emotionは表示しないこと
* DistractionとDrowsinessはregionの中央にメーター、左隣にアイコンを表示すること

## 成果物

リソースを切り貼りした画像イメージ
https://drive.google.com/open?id=14yI8EyVJTDJMnI741zr3ugf58ZJVtgMHQm1nOWtzJyw
(https://docs.google.com/drawings/ で作成してチームドライブに置くのがよさそう)

## 関連

#16 ストーリー: DMS展示画面イメージに近い見た目でデモを表示できる

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] イメージを作成する

**Comment by o0fatigue** [comment]
https://drive.google.com/open?id=14yI8EyVJTDJMnI741zr3ugf58ZJVtgMHQm1nOWtzJyw

**Comment by moritama312** [comment]
slackのやりとり(https://sensetime-jp.slack.com/archives/CD6HEJW94/p1542851170048100)でイメージに近くなったと言っていただいたので本issueの目的は達成できたと思います。
本issueはクローズします
