### ISSUE TITLE
ハンドジェスチャを検出し、結果をGUIに表示する

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#2]
## 概要

現時点の中国デモはハンドジェスチャが表示されない。
機能がデモに使えるか確認するため検出結果をGUIに表示する。

## 要件

* 日本版デモをリポジトリに用意すること
  * ハンドジェスチャを有効化する(すでに実装はある)
  * GUI上に検出した結果を表示する
    * ハンドジェスチャに関するリソース画像が元のリポジトリに残っていれば、それを利用する
    * 工数的に厳しければ数値/文字列出力のみでも可とする

## 成果物

対応したプロジェクト

## 関連

* issue #1 ストーリー: 一般向けDMSで提供できる機能が明らかになっている

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ハンドジェスチャ検出スレッドの有効化
* [x] リソース画像があるか/使えるか調査
* [x] GUI編集

**Comment by moritama312** [comment]
マージしたのでクローズします。

**Comment by nayutaya** [comment]
UI系のタスクは、「成果物」に「スクリーンショット」を含めておくと分かりやすくて良いかと思います。
