### ISSUE TITLE
RiskyActionに離席状態を表示する

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#21]
## 概要

RiskyActionのひとつとして、離席(顔が検出されない)状態を表示したい

## 要件

* 顔検出がN秒間継続して行われないときを離席状態とすること
* 顔検出に成功すると離席状態から脱すること
    * 一度最もシンプルな形で実装して、見てもらう

## 成果物

masterにマージされたプロジェクト

## 関連

#17 ストーリー: 離席状態を表示できる

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
~* [ ] 離席状態を扱うクラスor構造体を作成する~
~* [ ] 離席状態をアイコンで表示する~

**Comment by o0fatigue** [comment]
今の実装はクラスではなく、mainwindowのメンバー関数を追加する方法で実現しました。

**Comment by o0fatigue** [comment]
> 離席状態を扱うクラスor構造体を作成する
とのタスクですが、メンバー関数の追加で実現しました。

また、アイコンリソースを別のissueで実装します。

**Comment by moritama312** [comment]
マージしました。クローズします。
