### ISSUE TITLE
顔登録のUIを作成する

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#30]
## 概要

メイン画面で顔登録機能を追加する。

## 要件

* デモプログラムが動作中でも顔登録ができる（キーボード操作）。
* 顔情報（特徴量と画像）が削除できる。

## 成果物

* 要件を満たしたプログラム。

## 関連

#28 

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコード修正。
* [ ] masterにマージされる。

**Comment by o0fatigue** [comment]
一つ問題があります。顔特徴の削除機能を追加しましたが、もし全ての特徴を削除すると、
> features_in_database is NULL.
というエラーが出て、face_recog threadは中止となっています。つまり、特徴DBが空のとき、追加登録しようもなくなってしまいます。

これはSDKの仕様となり、 `dms-all/c-api/src/face_recog/dms_c_face_recog.cpp:286` にあります。

**Comment by moritama312** [comment]
マージしました。クローズします。
