### ISSUE TITLE
カメラ映像の表示アスペクト比を1280x1024相当に変更する

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#43]
## 概要

展示に用いるカメラ解像度が1280x1024であることがわかっている。
デモのカメラ映像表示領域をこの解像度に対応したアスペクト比に変更する

## 要件

* 1280x1024のカメラ映像をデモに入力したとき、正しいアスペクト比(5:4)で表示されること
* 1280x1024以外のカメラ映像を入力したとき、アスペクト比が仕様通りでないことがログに出力できること

## 成果物

要件を満たしたプログラムがmasterにマージされること

## 関連

* #42 ストーリー: 過去の指摘事項がデモに反映されている

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] 実装を修正する

**Comment by o0fatigue** [comment]
@moritama312 リソースブランチの上なので、リソースアップデートのissueを待っている状態です。なぜなら、rebaseをスムーズにできるように、できるだけレイアウト調整と機能調整をブランチ分けて作業しているからです。

**Comment by moritama312** [comment]
マージしました。クローズします。
