### ISSUE TITLE
SDKのステータスを使わずに、デモ側で段階を決める

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#62]
## 概要

DistractionとDrowsinessに関して、現状はSDKのLight/Medium/Heavyステータスを使っているので、SDKのconfigのパラメータ設定が分からない。デモ側でステータスを判断することによって、パラメータ調整できるようにする。

## 要件

* SDKが返したステータス結果を使わない。
* SDKが返した時間などを利用して、段階を決める。
* configureファイルでしきい値を設定できる。

## 成果物

* 要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [ ] ソースコードを修正する。
* [ ] masterにマージされる。

**Comment by moritama312** [comment]
あとでキャンセルの予定です

**Comment by moritama312** [comment]
#89 で DistractionとDrowsinessの各レベルの閾値について、SDK設定ファイル(config)と同等の設定をGUI設定ファイル(configure.json)に追加し、両者に同じ値を設定する運用で対応することにしました。
これにより本issueでの対応は不要となりました。クローズします。
