### ISSUE TITLE
顔の属性をスムージングする

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#63]
## 概要

現状では、顔の属性は頻繁に変わっている。より安定な表示を出すために、スムージング操作を行う。その前にまず調査が必要となる。すでにスムージングしている場合、スムーズパラメータを高める。スムージングがない場合、スムージング機能を入れる。

## 要件

* 顔の属性をより安定に表示できる。

## 成果物

要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコードを修正する。
* [x] masterにマージされる。

**Comment by moritama312** [comment]
マージしました。クローズします。
