### ISSUE TITLE
ショートカットを追加する

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#78]
## 概要

* メニューボタンの表示・非表示を制御する"M"キー
* Calibrationを制御する"C"キー
を追加する。

## 要件

以上のショートカットを追加する。

## 成果物

要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコードを修正する。
* [x] masterにマージする。

**Comment by moritama312** [comment]
マージ済です。
クローズします。
