### ISSUE TITLE
細かいレイアウト調整をする

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#83]
## 概要

展示要求に向けて、レイアウトを調整する。

## 要件

* 色が一致するアイコンを差し入れる。
* 製品名画像を実装する。
* 製品名の位置をロゴと合わせる。
* 属性の文字を大きくする。

## 成果物

要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコードを修正する。
* [x] masterにマージされる。

**Comment by o0fatigue** [comment]
![screenshot from 2018-12-21 17-51-08](https://user-images.githubusercontent.com/13743801/50333556-1257b480-0549-11e9-8a9d-ba86c553e0d6.png)

**Comment by moritama312** [comment]
マージしました。画面レイアウトはこれでFIXです。
細かい調整ありがとうございました。
クローズします。
