### ISSUE TITLE
Issueテンプレートをリポジトリに追加する

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#9]
## 概要

本リポジトリにIssueテンプレートを追加しIssueの作成を容易にする

## 要件

概要・要件・成果物・関連・タスクからなるテンプレートを追加する

## 成果物

本リポジトリでissueテンプレートが利用可能になる

## 関連

なし

## タスク

* [x] 付箋を貼り付ける
* [x] 概要、要件、成果物、関連、タスクを明確にする
* [x] Issueテンプレートを追加する #12

**Comment by nayutaya** [comment]
@moritama312 PR #12 のマージ後、レビューとクローズをお願いします。

**Comment by moritama312** [comment]
マージしました。
issue作成でテンプレートが表示されることを確認しました。
クローズします。
