### ISSUE TITLE
顔情報を削除した後、表示がしばらく変わらないことを修正する

### ISSUE THREAD

**Issue by o0fatigue** [sensetime-jp/dms-demo#97]
## 概要

現状では、顔情報を削除した後、表示する情報がしばらく変わらないこととなっています。この不具合を修正する。

## 要件

* 顔情報を削除した後、表示する情報をすぐ反映できるようにしたい。

## 成果物

* 要件を満たしたプログラム。

## 関連

なし。

## タスク

* [x] 付箋を貼り付ける。
* [x] 概要、要件、成果物、関連、タスクを明確にする。
* [x] ソースコードを修正する。
* [x] masterにマージする。

**Comment by o0fatigue** [comment]
* 顔情報を削除して、表示する情報がしばらく変わらないこと
* 映す人が変わっても、表示する情報がしばらく変わらないこと

以上2つの問題点に対して、調べた結果、顔認識のスムージング時間が長すぎるせいである。パラメータを80から30に調整することで、一応現時点の解決案となっている。

**Comment by moritama312** [comment]
マージしました。クローズします。
